### ISSUE TITLE
 "The type initializer for 'KSPe.1O.Hierarchy' threw an exception."

### ISSUE THREAD

**Issue by Ninluc** [net-lisias-ksp/KSPAPIExtensions#22] opened 2021-12-22 21:26 UTC
This is the error I have while loading ksp 1.12.3
![image](https://user-images.githubusercontent.com/56800521/147156910-6e1873d5-af43-456f-b394-f40e7c54e22c.png)

I only have TweakScale and the Module Manager /L Experimental installed

**Comment by Lisias** [comment] 2022-01-17 01:59
@Ninluc ,

*UGH*, I just noticed this today! Sorry by that. In the future, please mention my name using an `@` so Github notify me about it.

I need the KSP.log of the session, otherwise I will not be able to understand what's happening. It's probably something silly, as forgetting to install the `PluginData` subdirectory of KSPe.

I know for sure that it's not a bug on KSPe because I'm using it right now on every test bed on my rig, and I'm on a regression test where I firing up every single KSP version available on my rig (1.3.1, 1.4.x, 1.5.1, 1.6.1, 1.7.x, 1.8.1, 1.9.1., 1.10.1, 1.11.1, 1.12.x), and it's working on all of them.

After almost a month, I do not believe this is relevant anymore - but now I will monitor this issue closely if by any chance you still want assistance on this.

Cheers.

**Comment by Lisias** [comment] 2022-02-17 00:22
Closing this, as I don't think the user is coming back.

Additionally this appears to be a DUPLICATE from #27

**Closed by Lisias** 2022-02-17 00:22 UTC
Labels: support, WAITING
